### ISSUE TITLE
Server replies with 401: "Invalid publicKey"

### ISSUE THREAD

**Issue by x4121** [cpoppema/pass-server-node#1]
I created the key pair as described for the Chrome Extension, added it in gpg, set trust level and reencrypted the $password_store_dir with `pass init $oldKeys $newKeyId`.

When unlocking the key in the Extension or sending the publicKey with curl, the server returns "Invalid publicKey" (so it seems to be server-specific).

**Comment by cpoppema** [comment]
So, there is no debug or verbose option for the server (yet), I'll have to look into an easy way of implementing that as well.

Can you please checkout this (temporary) branch that might be able to help you out ? Looking forward to hear the results.

https://github.com/cpoppema/pass-server-node/tree/feature/add-verbose-option

Instead of starting the server with `npm start`, you can now start it with `NODE_ENV=testing npm start` and it should print some log statements to the console while starting up and when sending requests.

**Comment by x4121** [comment]
Seems like there is something getting mixed up during key lookup

```
store.js: configured password store directory is "$myPassDir".
store.js: keys in "$myPassDir/.gpg-id": $old1,$old2,0x9174510F1607714E
auth-middleware.js: request body contained a public key with id "9174510F1607714E".
store.js: looking for key id "9174510F1607714E" and key id "1607714E".
store.js: comparing against "$old1"..  is not a match
store.js: comparing against "$old2"..  is not a match
store.js: comparing against "0x9174510F1607714E"..  is not a match
auth-middleware.js: no matching key id was found in "$myPassDir/.gpg-id".
```

**Comment by x4121** [comment]
Ah OK, I got it... I initialized with a leading `0x...` and it looks for a perfekt match.
After re-initializing without `0x..` it works.

**Comment by cpoppema** [comment]
Thanks for sharing your results, to be honest I never thought of adding the `0x` or `0` prefix, but I'm sure I can put that in easily.
