### ISSUE TITLE
Choice of store organization

### ISSUE THREAD

**Issue by DamienCassou** [cpoppema/pass-server-node#3]
I'm one of the authors of passwe, an alternative to your implementation with a [web-extension plugin](https://gitlab.petton.fr/passwe/passwe-addon) and a [native application in nodejs](https://gitlab.petton.fr/passwe/passwe-app). I was wondering if I could contribute to your project instead of going my own way. However, I rapidly found out that your solution uses `<url>/<username>` as entry names which is not recommended by https://www.passwordstore.org/. Is this organization written in stone or do you have any wish to make your code accept more options?

**Comment by cpoppema** [comment]
Thanks for asking! I found that there isn't really one recommended way by `pass` itself. Most examples look like `Category/username`, but the manpage (also referred on that website) uses `Name/username` in the [extended git example](https://git.zx2c4.com/password-store/about/), e.g. `Amazon/amazonemail@email.com`. I adopted it to `domain/username` (so with the same example it looks like `amazon.com/amazonemail@email.com`) since I was primarily looking for it to function as a plugin with form-fill functionality which would benefit greatly from being able to match domain names with secrets.

To given an answer your question: No, it's not set in stone and if you want, you can perhaps make a proposal and we'll take it from there :).
